# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-20 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models
import otree_save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('choice_1', otree.db.models.StringField(choices=[('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], max_length=10000, null=True)),
                ('choice_2', otree.db.models.StringField(choices=[('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], max_length=10000, null=True)),
                ('choice_3', otree.db.models.StringField(choices=[('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], max_length=10000, null=True)),
                ('round_1_winner', otree.db.models.StringField(choices=[('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], max_length=10000, null=True)),
                ('winner', otree.db.models.StringField(max_length=10000, null=True)),
                ('committee', otree.db.models.IntegerField(null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_2_group', to='otree.Session')),
            ],
            options={
                'db_table': 'agenda_2_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('role', otree.db.models.StringField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10000, null=True)),
                ('vote_1', otree.db.models.StringField(choices=[('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], max_length=10000, null=True)),
                ('vote_2', otree.db.models.StringField(choices=[('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], max_length=10000, null=True)),
                ('committee', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda_2.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_2_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_2_player', to='otree.Session')),
            ],
            options={
                'db_table': 'agenda_2_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda_2_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'agenda_2_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda_2.Subsession'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda_2.Subsession'),
        ),
    ]
