# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-20 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models
import otree_save_the_change.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('total_contribution', otree.db.models.CurrencyField(null=True)),
                ('individual_share', otree.db.models.CurrencyField(null=True)),
                ('average_contribution', otree.db.models.CurrencyField(null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_goods_cond_group', to='otree.Session')),
            ],
            options={
                'db_table': 'public_goods_cond_group',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_arrived', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('contribution', otree.db.models.CurrencyField(null=True)),
                ('kept', otree.db.models.CurrencyField(null=True)),
                ('cond_cont0', otree.db.models.CurrencyField(null=True)),
                ('cond_cont1', otree.db.models.CurrencyField(null=True)),
                ('cond_cont2', otree.db.models.CurrencyField(null=True)),
                ('cond_cont3', otree.db.models.CurrencyField(null=True)),
                ('cond_cont4', otree.db.models.CurrencyField(null=True)),
                ('cond_cont5', otree.db.models.CurrencyField(null=True)),
                ('cond_cont6', otree.db.models.CurrencyField(null=True)),
                ('cond_cont7', otree.db.models.CurrencyField(null=True)),
                ('cond_cont8', otree.db.models.CurrencyField(null=True)),
                ('cond_cont9', otree.db.models.CurrencyField(null=True)),
                ('cond_cont10', otree.db.models.CurrencyField(null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='public_goods_cond.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_goods_cond_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_goods_cond_player', to='otree.Session')),
            ],
            options={
                'db_table': 'public_goods_cond_player',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='public_goods_cond_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'public_goods_cond_subsession',
            },
            bases=(otree_save_the_change.mixins.SaveTheChange, models.Model),
        ),
        migrations.AddField(
            model_name='player',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_goods_cond.Subsession'),
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_goods_cond.Subsession'),
        ),
    ]
